### PR TITLE
add coverage to CI

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
see https://codecov.io/github/kokkos/kokkos-fortran-interop/commit/781220c2b96d7f0acd8c8ed835c435bfc886fc96, I am not sure if the @codecov will comment or if an org admin has to enable that.

**Comment by womeld** [comment]
Is there an action item here for me? If so, just let me know.

**Comment by junghans** [comment]
I think you can just merge this.

**Comment by junghans** [comment]
@dalg24 could you enable the codecov.io plugin for this repo?

**Pull request merged**
